theme: jekyll-theme-cayman
lang: en_US

title: Baoshuo's Site
# description: Baoshuo's Site
Author: Ren Baoshuo
image: 
  path: /assets/images/Avatar.png
  height: 200
  width: 200

# 显示下载按钮
show_downloads: false

# 谷歌统计
google_analytics: UA-163290903-7

# Github 设置
github: 
  is_project_page: false


plugins:
  - jekyll-sitemap

# 友情链接
links: 
  - name: "LiCEO"
    link: "https://lsc.moe/"
  - name: "Berd's Playground"
    link: "https://blog.berd.moe/"

# 菜单栏
menus: 
  - 0: 
    name: Home
    link: /
  - 1: 
    name: About
    link: /about.html
  - 2: 
    name: Others
    link: https://renbaoshuo.github.io

# Twitter
twitter:
  card: summary
  username: renbaoshuo

# Facebook
# facebook:
#   admins: 

# 站点验证
webmaster_verifications:
  google: QPAs-WvnzBF_40NLGcMWRcWGLpEvskzSbo1oYv4P2uU

# 社交信息
social:
  name: Ren Baoshuo
  links:
    - https://twitter.com/renbaoshuo
    - https://www.facebook.com/renbaoshuo
    - https://www.linkedin.com/in/renbaoshuo
    - https://github.com/renbaoshuo
    - https://t.me/baoshuo
